### PR TITLE
Integrate 'Order Support' and 'Batch ProductDetails' APIs

### PR DESCRIPTION
**Pull request by Funkenjaeger**
Also a fix for issue #8

### CODE REVIEW

**Comment by peeter123** [comment]
Thanks @Funkenjaeger, I will try to look into this coming weekend.

Could you elaborate a bit what you did with regard to Order Support and Batch Productdetails? 

I guess (looking at the commits) you just extended the swagger API generation script with these APIs and generated the API again?

Maybe you could split up (Resolve issue #8) and (Integrate 'Order Support' and 'Batch ProductDetails' APIs) into two separate pull requests?

**Comment by Funkenjaeger** [comment]
@peeter123, yes, I did those things and updated digikey/v3/api.py
accordingly: Revised `ProductApiWrapper` to a more generic
`DigikeyApiWrapper` to cover all three of the supported Digikey APIs, and
added `status_salesorder_id()`, `salesorder_history()` and
`batch_product_details()` functions to use the two added Digikey APIs.

The fix for #8 is a trivial one-liner - I could create a separate pull
request if you want, or you could just make the same change on your end.

Disclaimer: I'm a relative Python novice, I won't be offended if you'd
rather not take my PR because of the way I elected to implement the changes
- I just wanted to offer it up.
Either way I really appreciate you making this library to begin with.

**Comment by peeter123** [comment]
Great, thanks for your comments and effort! I am a Python novice myself as well and created this library to help with some hobby projects :)

I have merged your changes in master and will need to do a bit more tests before releasing a new version on PyPI.

**Comment by eeintech** [comment]
@peeter123 Why not merging this PR?

**Comment by peeter123** [comment]
@eeintech What do you mean? I have already merged the changes into master via git commandline.

**Comment by eeintech** [comment]
Ha nevermind, I missed your previous message, I just saw this PR got closed, all good :+1:

**Pull request closed without merging**
